name: Fetch Domains and Generate Source File (Weekly)

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday.
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fetch Domains and generate source file
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: npm run fetch-domains

      - name: Commit generated source
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/data/domains.ts data/domains.txt
          git commit -m "Weekly Domain update"
          git push